
networks:
  tabela-precos-net:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    working_dir: /app/api
    command: node server.js
    ports:
      - "3001:3001"
    networks:
      - tabela-precos-net
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    working_dir: /app/tela-valores
    command: npm run dev -- --host
    ports:
      - "5173:5173" 
    networks:
      - tabela-precos-net
    restart: unless-stopped
