version: "3.9"

networks:
  tabela-precos-net:
    external: true
  traefik-net:
    external: false

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"                       # Painel do Traefik (HTTP)
      - "--providers.docker=true"                   # Habilita integração com Docker
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=seu-email@dominio.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "7080:80"
      - "7443:443"
      - "8580:8080"   # Dashboard Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik-net
      - tabela-precos-net
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    working_dir: /app/api
    command: node server.js
    networks:
      - tabela-precos-net
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`closedasapp.motoclubehonda.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=3001"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    working_dir: /app/tela-valores
    command: npm run dev -- --host
    networks:
      - tabela-precos-net
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`closedasapp.motoclubehonda.com.br`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    restart: unless-stopped
