version: "3.7"

networks:
  network_public:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    working_dir: /app/api
    command: node server.js
    networks:
      - network_public
    labels:
      - traefik.enable=1
      - traefik.http.routers.closedasapp_api.rule=Host(`closedasapp.motoclubehonda.com.br`) && PathPrefix(`/api`)
      - traefik.http.routers.closedasapp_api.entrypoints=websecure
      - traefik.http.routers.closedasapp_api.tls.certresolver=letsencryptresolver
      - traefik.http.services.closedasapp_api.loadbalancer.server.port=3001
      - traefik.http.services.closedasapp_api.loadbalancer.passHostHeader=true
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    working_dir: /app/tela-valores
    command: npm run dev -- --host
    networks:
      - network_public
    labels:
      - traefik.enable=1
      - traefik.http.routers.closedasapp_frontend.rule=Host(`closedasapp.motoclubehonda.com.br`) && PathPrefix(`/`) 
      - traefik.http.routers.closedasapp_frontend.entrypoints=websecure
      - traefik.http.routers.closedasapp_frontend.tls.certresolver=letsencryptresolver
      - traefik.http.services.closedasapp_frontend.loadbalancer.server.port=5173
      - traefik.http.services.closedasapp_frontend.loadbalancer.passHostHeader=true
    restart: unless-stopped
